version: 1.0.{build}
skip_non_tags: false
build_script:
- ps: .\build.ps1
test: off
branches:
  only: 
  - master
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: Jp5g6Py44Rh01e4zCeqOptcHH8wlt3dyCpVPZ+V6bvBoRwvI3W6lMZOeas2x/H4D
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: true
notifications:
- provider: Email
  to:
  - lr.antunes@gmail.com
  subject: Mvc.RazorFeatures Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false