version: 1.0.{build}
skip_non_tags: false
build_script:
- ps: .\build.ps1
test: off
branches:
  only: 
  - master
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
notifications:
- provider: Email
  to:
  - lr.antunes@gmail.com
  subject: UseNodeModules Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false